name: ORBIT Agent (Telegram Manual)
on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours (00:00, 02:00, 04:00, 06:00, 08:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00 UTC)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install python-dotenv
          python -m playwright install --with-deps chromium

      - name: Download state from previous run
        uses: actions/download-artifact@v4
        with:
          name: telegram-state-json
          path: .
        continue-on-error: true

      - name: Process Telegram Messages
        run: |
          python -m src.telegram_processor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          TOPICS: ${{ secrets.TOPICS }}
          ALLOWLIST: ${{ secrets.ALLOWLIST }}

      - name: Upload state (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: telegram-state-json
          path: state.json
          if-no-files-found: ignore
