name: Schedule 12x Autopost (PAUSED)
on:
  # schedule:
  #   - cron: "0 */2 * * *"  # PAUSED - rate limit issues
  workflow_dispatch: {}  # Manual trigger only
jobs:
  run-autopost-once:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir ~/.cache/pip -r requirements.txt
          pip install --cache-dir ~/.cache/pip playwright
          python -m playwright install --with-deps chromium

      - name: Env
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_KEY_SECRET=${{ secrets.API_KEY_SECRET }}" >> $GITHUB_ENV
          echo "X_ACCESS_TOKEN=${{ secrets.X_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "X_ACCESS_SECRET=${{ secrets.X_ACCESS_SECRET }}" >> $GITHUB_ENV
          echo "TOPICS=\$POL" >> $GITHUB_ENV
          echo "MIN_REPLIES=10" >> $GITHUB_ENV
          echo "MIN_FAVES=10" >> $GITHUB_ENV
          echo "SEARCH_HOURS=12" >> $GITHUB_ENV
          echo "DRY_RUN=false" >> $GITHUB_ENV
          echo "MAX_POSTS=1" >> $GITHUB_ENV

      - name: Run single autopost (API path)
        run: |
          python -m src.smoke_scrape
